### ISSUE TITLE
Phone inputs should allow hyphens and parentheses

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#562] opened 2020-06-09 21:05 UTC
See related https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/561. Vero confirmed it was the hyphens

**Comment by joeldenning** [comment] 2020-06-22 22:44
This includes when adding and updating both clients and leads.

**Comment by leahjlou** [comment] 2020-06-23 02:25
Could not reproduce for adding/editing clients or leads. Parens and hyphens were all OK. Closing this.

**Closed by leahjlou** 2020-06-23 02:25 UTC
