### ISSUE TITLE
database

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#535] opened 2020-05-28 18:23 UTC
From: Alex Taylor, alex.taylor@cuutah.org

Information about error: 

{
    "error": "Api request to '/api/leads/375' failed with HTTP status 400\nError: Api request to '/api/leads/375' failed with HTTP status 400\n    at https://database.cuutah.org/static/comunidades-unidas-internal.a6ac3546946996ffe50e.js:2:365880",
    "message": "Uncaught Error: Api request to '/api/leads/375' failed with HTTP status 400",
    "filename": "https://database.cuutah.org/static/comunidades-unidas-internal.a6ac3546946996ffe50e.js",
    "lineno": 2,
    "colno": 638501
}

**Comment by joeldenning** [comment] 2020-05-28 18:52
Duplicate of #536

**Closed by joeldenning** 2020-05-28 18:52 UTC
