### ISSUE TITLE
error en interaccion

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#329] opened 2019-10-09 17:31 UTC
From: teodora garcia, teo@cuutah.org

Information about error: 

{
    "error": "The user aborted a request.\nundefined",
    "message": "Uncaught AbortError: The user aborted a request.",
    "filename": "https://database.cuutah.org/static/comunidades-unidas-internal.6e33486757a29125bd04.js",
    "lineno": 49,
    "colno": 492786
}

**Comment by joeldenning** [comment] 2019-10-09 17:45
Closing as a duplicate of #328 which shows more detail about the error.

**Closed by joeldenning** 2019-10-09 17:45 UTC
