### ISSUE TITLE
cities other than slc were crashing the site during add client demo at cu meeting

### ISSUE THREAD

**Issue by MeghanBomberger** [JustUtahCoders/comunidades-unidas-internal#118] opened 2019-06-03 20:12 UTC

**Comment by MeghanBomberger** [comment] 2019-06-04 04:07
I haven't been able to duplicate the error the woman ran into during the meeting.

**Comment by joeldenning** [comment] 2019-06-06 00:59
I'm also unable to reproduce. Unless/until we can, I'm going to close this.

**Closed by joeldenning** 2019-06-06 00:59 UTC
