### ISSUE TITLE
Problema no pasa a sicresal 

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#848] opened 2021-11-08 21:10 UTC
From: Araceli de la sancha , oooo@gmail.com

Information about error: 

{
    "error": null,
    "message": "Script error.",
    "filename": "",
    "lineno": 0,
    "colno": 0
}

**Comment by joeldenning** [comment] 2021-11-09 18:08
duplicate of #846

**Closed by joeldenning** 2021-11-09 18:08 UTC
