### ISSUE TITLE
call update

### ISSUE THREAD

**Issue by justutahcoders-guest** [JustUtahCoders/comunidades-unidas-internal#478] opened 2020-04-06 22:06 UTC
From: virginia fuentes, vicky@cuutah.org

Information about error: 

{
    "error": "Api request to '/api/leads/147' failed with HTTP status 400\nError: Api request to '/api/leads/147' failed with HTTP status 400\n    at https://database.cuutah.org/static/comunidades-unidas-internal.3860fd967de145d125ba.js:2:221025",
    "message": "Uncaught Error: Api request to '/api/leads/147' failed with HTTP status 400",
    "filename": "https://database.cuutah.org/static/comunidades-unidas-internal.3860fd967de145d125ba.js",
    "lineno": 2,
    "colno": 463711
}

**Comment by joeldenning** [comment] 2020-04-07 20:20
Fixed in https://github.com/JustUtahCoders/comunidades-unidas-internal/commit/29c3877c96a1fa9876ad13376ef6765d9f39a58f. Same root cause as #479

**Closed by joeldenning** 2020-04-07 20:20 UTC
